/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import simulationfeuvrai.SimulationFeuvrai;
import simulationfeuvrai.Case;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author elora
 */
public class Fenetre2 extends javax.swing.JDialog {

    private Simulation simu;
    private Information fichInfo;
    private Entree fichEntree;
    private int nbr;
    private String sens;
    private String humidite;
    private String vent;
    private int taille;
    /**
     * Creates new form Fenetre2
     */
    public Fenetre2(javax.swing.JDialog parent, boolean modal, String sens, String vent, String humidite, double nbr,int ligne,int colonne,int taille) throws IOException {
        super(parent, modal);
        this.taille = taille;
        setTitle("Simulation Feu");    //on donne un nom à notre fenêtre
        initComponents();
        BRelancer.setVisible(false);   //on efface le bouton BRelancer qui ne sera visisble qu'à la fin de la simu
        BRelancer.setEnabled(false);
        setLocationRelativeTo(parent);    //on place notre fenêtre au même endroit que la fiche Information, c'est à dire au centre de l'écran
        simu = new Simulation(sens, vent, humidite, nbr, ligne, colonne,taille);
        simu.setLocation(50,50);               //on place le terrain aux coordonnées 50x50
        jLabel1.setText("Pourcentage de végétation du terrain : "+(nbr*100)+"%");
        jLabel3.setText("Vent venant de : "+sens);
        jLabel4.setText("Force du vent : "+vent);
        jLabel5.setText("Humidite du terrain : "+humidite);
        jPanel2.add(simu);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BDemarrer = new javax.swing.JButton();
        BRelancer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(230, 240, 240));

        jPanel2.setBackground(new java.awt.Color(230, 240, 240));

        jPanel1.setBackground(new java.awt.Color(230, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(230, 240, 240));

        jLabel3.setBackground(new java.awt.Color(230, 240, 240));

        jLabel1.setBackground(new java.awt.Color(230, 240, 240));

        jLabel4.setBackground(new java.awt.Color(230, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BDemarrer.setBackground(new java.awt.Color(255, 255, 255));
        BDemarrer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        BDemarrer.setForeground(new java.awt.Color(255, 153, 51));
        BDemarrer.setText("Démarrer");
        BDemarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDemarrerActionPerformed(evt);
            }
        });

        BRelancer.setBackground(new java.awt.Color(255, 255, 255));
        BRelancer.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        BRelancer.setForeground(new java.awt.Color(255, 153, 51));
        BRelancer.setText("Relancer une simulation");
        BRelancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRelancerActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(230, 240, 240));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BRelancer)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BDemarrer)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(BDemarrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BRelancer)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRelancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRelancerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichInfo=new Information (fichEntree,false);
        fichInfo.setVisible(true);
    }//GEN-LAST:event_BRelancerActionPerformed

    private void BDemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDemarrerActionPerformed
        // TODO add your handling code here:
        BDemarrer.setEnabled(false);
        new Thread() {
            public void run() {
                BRelancer.setVisible(false);
                BRelancer.setEnabled(false);
                SimulationFeuvrai sf = simu.gets();
                try {
                    Thread.sleep(500);        //pause de 500ms avant de refresh le terrain
                } catch (InterruptedException ex) {
                    Logger.getLogger(Fenetre2.class.getName()).log(Level.SEVERE, null, ex);
                }
                while (sf.verif(sf.getForest(), taille)) {   //verifier que la simu ne soit pas terminée
                    BRelancer.setVisible(false);
                    BRelancer.setEnabled(false);
                    jLabel2.setText("");

                    sf.pasapas(sf.getForest(), sf.getClimat(),taille);   //appelle la méthode qui fait avancer pas à pas
                    jLabel2.setText("Nombre de parcelles de terrain brûlées : " +sf.nbrCaseBrulees(sf.getForest(),taille)+" ");
                    repaint();
                    try {
                        Thread.sleep(500);       //pause de 500ms
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Fenetre2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    sf.Fichiertext2(taille);    //on appelle la méthode qui écrit dans le fichier texte le pourcentage de cases qui à brûlé
                } catch (IOException ex) {
                    Logger.getLogger(Fenetre2.class.getName()).log(Level.SEVERE, null, ex);
                }
                BRelancer.setVisible(true);
                BRelancer.setEnabled(true);
            }
        }.start();
    }//GEN-LAST:event_BDemarrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Information dialog = new Information(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDemarrer;
    private javax.swing.JButton BRelancer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
