/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfiches;
import java.io.IOException;
import static java.lang.Math.sqrt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import simulationfeuvrai.SimulationFeuvrai;
/**
 *
 * @author Hajar
 */
public class Information extends javax.swing.JDialog {
    private Fenetre2 fichFenetre;
    private SimulationFeuvrai s;
    private Simulation fichSimulation;
    
    public Information(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        field1.setVisible(false);
        field2.setVisible(false);
        nomfield1.setVisible(false);
        nomfield2.setVisible(false);
        setLocationRelativeTo(parent);    //on place notre fenêtre au même endroit que la fiche Entree, c'est à dire au centre de l'écran
        setTitle("Simulation Feu");
        
    }
    String vent;
    String sens;
    String humidite;
    double nbr;
    
    public void popup (){
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Veuillez sélectionner tous les critères ");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jFond1 = new javax.swing.JPanel();
        PChif4 = new javax.swing.JPanel();
        rbClairsemee = new javax.swing.JRadioButton();
        rbEspacee = new javax.swing.JRadioButton();
        rbTouffue = new javax.swing.JRadioButton();
        rbContinue = new javax.swing.JRadioButton();
        IVege = new javax.swing.JLabel();
        pChif2 = new javax.swing.JPanel();
        IVent2 = new javax.swing.JLabel();
        rbNord = new javax.swing.JRadioButton();
        rbSud = new javax.swing.JRadioButton();
        rbEst = new javax.swing.JRadioButton();
        rbOuest = new javax.swing.JRadioButton();
        field1 = new javax.swing.JTextField();
        field2 = new javax.swing.JTextField();
        pChif1 = new javax.swing.JPanel();
        IVent1 = new javax.swing.JLabel();
        rbNul = new javax.swing.JRadioButton();
        rbModere = new javax.swing.JRadioButton();
        rbFort = new javax.swing.JRadioButton();
        rbViolent = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSlider1 = new javax.swing.JSlider();
        nomfield1 = new javax.swing.JLabel();
        nomfield2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bValider = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbHumide = new javax.swing.JRadioButton();
        rbNormal = new javax.swing.JRadioButton();
        rbSec = new javax.swing.JRadioButton();
        rbTresSec = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFond1.setBackground(new java.awt.Color(230, 240, 240));
        jFond1.setForeground(new java.awt.Color(255, 255, 255));
        jFond1.setMaximumSize(new java.awt.Dimension(0, 0));

        PChif4.setBackground(new java.awt.Color(0, 0, 0));
        PChif4.setForeground(new java.awt.Color(255, 102, 0));
        PChif4.setOpaque(false);

        rbClairsemee.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup4.add(rbClairsemee);
        rbClairsemee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbClairsemee.setForeground(new java.awt.Color(255, 153, 51));
        rbClairsemee.setText("Clairsemée");
        rbClairsemee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClairsemeeActionPerformed(evt);
            }
        });

        rbEspacee.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup4.add(rbEspacee);
        rbEspacee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbEspacee.setForeground(new java.awt.Color(255, 153, 51));
        rbEspacee.setText("Espacée");
        rbEspacee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEspaceeActionPerformed(evt);
            }
        });

        rbTouffue.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup4.add(rbTouffue);
        rbTouffue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTouffue.setForeground(new java.awt.Color(255, 153, 51));
        rbTouffue.setText("Touffue");
        rbTouffue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTouffueActionPerformed(evt);
            }
        });

        rbContinue.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup4.add(rbContinue);
        rbContinue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbContinue.setForeground(new java.awt.Color(255, 153, 51));
        rbContinue.setText("Continue");
        rbContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbContinueActionPerformed(evt);
            }
        });

        IVege.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IVege.setText("Végétation du terrain  ");

        javax.swing.GroupLayout PChif4Layout = new javax.swing.GroupLayout(PChif4);
        PChif4.setLayout(PChif4Layout);
        PChif4Layout.setHorizontalGroup(
            PChif4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PChif4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PChif4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbClairsemee)
                    .addComponent(rbEspacee)
                    .addComponent(rbTouffue)
                    .addComponent(rbContinue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PChif4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(IVege)
                .addContainerGap())
        );
        PChif4Layout.setVerticalGroup(
            PChif4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PChif4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(IVege)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbClairsemee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbEspacee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTouffue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbContinue)
                .addGap(23, 23, 23))
        );

        pChif2.setBackground(new java.awt.Color(0, 0, 0));
        pChif2.setOpaque(false);

        IVent2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IVent2.setText("Sens du vent ");

        rbNord.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup2.add(rbNord);
        rbNord.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNord.setForeground(new java.awt.Color(255, 153, 51));
        rbNord.setText("Nord");
        rbNord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNordActionPerformed(evt);
            }
        });

        rbSud.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup2.add(rbSud);
        rbSud.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbSud.setForeground(new java.awt.Color(255, 153, 51));
        rbSud.setText("Sud");
        rbSud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSudActionPerformed(evt);
            }
        });

        rbEst.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup2.add(rbEst);
        rbEst.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbEst.setForeground(new java.awt.Color(255, 153, 51));
        rbEst.setText("Est");

        rbOuest.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup2.add(rbOuest);
        rbOuest.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbOuest.setForeground(new java.awt.Color(255, 153, 51));
        rbOuest.setText("Ouest");
        rbOuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pChif2Layout = new javax.swing.GroupLayout(pChif2);
        pChif2.setLayout(pChif2Layout);
        pChif2Layout.setHorizontalGroup(
            pChif2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChif2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pChif2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChif2Layout.createSequentialGroup()
                        .addGroup(pChif2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNord)
                            .addComponent(rbSud)
                            .addComponent(rbEst)
                            .addComponent(rbOuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pChif2Layout.createSequentialGroup()
                        .addComponent(IVent2)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        pChif2Layout.setVerticalGroup(
            pChif2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChif2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(IVent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbEst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOuest)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        field1.setToolTipText("");
        field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field1ActionPerformed(evt);
            }
        });

        field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field2ActionPerformed(evt);
            }
        });

        pChif1.setBackground(new java.awt.Color(230, 240, 240));
        pChif1.setForeground(new java.awt.Color(255, 255, 255));

        IVent1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IVent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IVent1.setText("Force du vent ");

        rbNul.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup1.add(rbNul);
        rbNul.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbNul.setForeground(new java.awt.Color(255, 153, 51));
        rbNul.setText("Nul");
        rbNul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNulActionPerformed(evt);
            }
        });

        rbModere.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup1.add(rbModere);
        rbModere.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbModere.setForeground(new java.awt.Color(255, 153, 51));
        rbModere.setText("Modéré");
        rbModere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModereActionPerformed(evt);
            }
        });

        rbFort.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup1.add(rbFort);
        rbFort.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbFort.setForeground(new java.awt.Color(255, 153, 51));
        rbFort.setText("Fort");
        rbFort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFortActionPerformed(evt);
            }
        });

        rbViolent.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup1.add(rbViolent);
        rbViolent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbViolent.setForeground(new java.awt.Color(255, 153, 51));
        rbViolent.setText("Violent");
        rbViolent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViolentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pChif1Layout = new javax.swing.GroupLayout(pChif1);
        pChif1.setLayout(pChif1Layout);
        pChif1Layout.setHorizontalGroup(
            pChif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChif1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pChif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNul)
                    .addComponent(rbModere)
                    .addComponent(rbFort)
                    .addComponent(rbViolent)
                    .addComponent(IVent1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pChif1Layout.setVerticalGroup(
            pChif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChif1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(IVent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbModere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbViolent)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Veuillez remplir les informations");
        jLabel2.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brûler 2 cases aléatoirement", "Choisir les coordonnées de la case à brûler" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSlider1.setBackground(new java.awt.Color(230, 240, 240));
        jSlider1.setMajorTickSpacing(400);
        jSlider1.setMaximum(900);
        jSlider1.setMinimum(100);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(500);

        nomfield1.setText("Ligne :");

        nomfield2.setText("Colonne :");

        jLabel1.setText("Nombre de cases sur le terrain ");

        jLabel3.setText("900");

        jLabel4.setText(" 400");

        jLabel5.setText("           100");

        bValider.setBackground(new java.awt.Color(255, 255, 255));
        bValider.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        bValider.setForeground(new java.awt.Color(255, 153, 51));
        bValider.setText("Lancer la simulation");
        bValider.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 240, 240));

        rbHumide.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup5.add(rbHumide);
        rbHumide.setForeground(new java.awt.Color(255, 153, 51));
        rbHumide.setText("Humide");
        rbHumide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHumideActionPerformed(evt);
            }
        });

        rbNormal.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup5.add(rbNormal);
        rbNormal.setForeground(new java.awt.Color(255, 153, 51));
        rbNormal.setText("Normal");

        rbSec.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup5.add(rbSec);
        rbSec.setForeground(new java.awt.Color(255, 153, 51));
        rbSec.setText("Sec");

        rbTresSec.setBackground(new java.awt.Color(230, 240, 240));
        buttonGroup5.add(rbTresSec);
        rbTresSec.setForeground(new java.awt.Color(255, 153, 51));
        rbTresSec.setText("Très Sec");

        jLabel6.setBackground(new java.awt.Color(230, 240, 240));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Humidité");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNormal)
                    .addComponent(rbSec)
                    .addComponent(rbTresSec)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbHumide, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbHumide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbTresSec))
        );

        javax.swing.GroupLayout jFond1Layout = new javax.swing.GroupLayout(jFond1);
        jFond1.setLayout(jFond1Layout);
        jFond1Layout.setHorizontalGroup(
            jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFond1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2))
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addComponent(pChif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pChif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PChif4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
            .addGroup(jFond1Layout.createSequentialGroup()
                .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFond1Layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFond1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(nomfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(bValider, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFond1Layout.setVerticalGroup(
            jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFond1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addComponent(pChif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFond1Layout.createSequentialGroup()
                        .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFond1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFond1Layout.createSequentialGroup()
                                .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PChif4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pChif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomfield1)
                            .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomfield2)
                            .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(bValider, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFond1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFond1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        //on clique su le bouton et on affiche la fenetre information
        if (rbNul.isSelected()) {
            vent = "nul";
        } else if (rbModere.isSelected()) {
            vent = "modéré";
        } else if (rbFort.isSelected()) {
            vent = "fort";
        }else if (rbViolent.isSelected()) {
            vent = "violent";}

        if (rbNord.isSelected()) {
            sens = "nord";
        } else if (rbSud.isSelected()) {
            sens = "sud";
        } else if (rbOuest.isSelected()) {
            sens = "ouest";
        }else if (rbEst.isSelected()) {
            sens = "est";}

        if (rbHumide.isSelected()) {
            humidite = "humide";
        } else if (rbNormal.isSelected()) {
            humidite = "normal";
        } else if (rbSec.isSelected()) {
            humidite = "sec";
        }else if (rbTresSec.isSelected()) {
            humidite = "très sec";}

        if (rbClairsemee.isSelected()) {
            nbr=0.5;
        } else if (rbEspacee.isSelected()) {
            nbr=0.75;
        } else if (rbTouffue.isSelected()) {
            nbr=0.9;
        }else if (rbContinue.isSelected()) {
            nbr=1;}

        if (vent == null || sens == null || nbr == 0 || humidite == null){
            System.out.println(humidite);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Veuillez sélectionner tous les critères ");
            return;                    //permet de sortir de la méthode
        }
        int taille = jSlider1.getValue();
        if (taille==500) {
            taille=400;
        }
        int ligne = 1000;
        int colonne = 1000;
        if (jComboBox1.getSelectedItem().toString().equals("Choisir les coordonnées de la case à brûler")) {
            String ligne1 = field1.getText();
            boolean ligne1num =  ligne1.matches("[+-]?\\d*(\\.\\d+)?");
            String colonne1 = field2.getText();
            boolean colonne1num =  colonne1.matches("[+-]?\\d*(\\.\\d+)?");
            if (colonne1num==false || ligne1num==false) {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Veuillez rentrer un nombre valide");
                return;
            }
            ligne = Integer.parseInt(ligne1);
            colonne = Integer.parseInt(colonne1);
            if (ligne>sqrt(taille) || ligne<0 || colonne>sqrt(taille) || colonne<0) {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Veuillez rentrer des nombres entre 0 et "+sqrt(taille));
                return;
            }

        }
        try {
            fichFenetre = new Fenetre2 (this,false,sens, vent, humidite, nbr,ligne,colonne,taille);
        } catch (IOException ex) {
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setVisible(false);
        fichFenetre.setVisible(true);
    }//GEN-LAST:event_bValiderActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int ligne;
        int colonne;
        if (jComboBox1.getSelectedItem().toString().equals("Brûler 2 cases aléatoirement")) {
            ligne = 1000;
            colonne = 1000;
            field1.setVisible(false);
            field2.setVisible(false);
            nomfield1.setVisible(false);
            nomfield2.setVisible(false);

        } else {
            field1.setVisible(true);
            field2.setVisible(true);
            nomfield1.setVisible(true);
            nomfield2.setVisible(true);
        }
        jComboBox1.revalidate();   //permet de refresh
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rbViolentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViolentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViolentActionPerformed

    private void rbFortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFortActionPerformed

    private void rbModereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbModereActionPerformed

    private void rbNulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNulActionPerformed
        // la force du vent est nulle
    }//GEN-LAST:event_rbNulActionPerformed

    private void field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field2ActionPerformed

    private void field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field1ActionPerformed

    private void rbOuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOuestActionPerformed

    private void rbSudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSudActionPerformed

    private void rbNordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNordActionPerformed

    private void rbContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbContinueActionPerformed

    private void rbTouffueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTouffueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTouffueActionPerformed

    private void rbEspaceeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEspaceeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEspaceeActionPerformed

    private void rbClairsemeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClairsemeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbClairsemeeActionPerformed

    private void rbHumideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHumideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHumideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Information dialog = new Information(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IVege;
    private javax.swing.JLabel IVent1;
    private javax.swing.JLabel IVent2;
    private javax.swing.JPanel PChif4;
    private javax.swing.JButton bValider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jFond1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel nomfield1;
    private javax.swing.JLabel nomfield2;
    private javax.swing.JPanel pChif1;
    private javax.swing.JPanel pChif2;
    private javax.swing.JRadioButton rbClairsemee;
    private javax.swing.JRadioButton rbContinue;
    private javax.swing.JRadioButton rbEspacee;
    private javax.swing.JRadioButton rbEst;
    private javax.swing.JRadioButton rbFort;
    private javax.swing.JRadioButton rbHumide;
    private javax.swing.JRadioButton rbModere;
    private javax.swing.JRadioButton rbNord;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbNul;
    private javax.swing.JRadioButton rbOuest;
    private javax.swing.JRadioButton rbSec;
    private javax.swing.JRadioButton rbSud;
    private javax.swing.JRadioButton rbTouffue;
    private javax.swing.JRadioButton rbTresSec;
    private javax.swing.JRadioButton rbViolent;
    // End of variables declaration//GEN-END:variables
}
