/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfiches;
import java.awt.Color;
import simulationfeuvrai.SimulationFeuvrai;
import simulationfeuvrai.Terrain;

import java.awt.Graphics;
import java.io.IOException;
import static java.lang.Math.sqrt;
import javax.swing.JFrame;
import simulationfeuvrai.Case;

/**
 *
 * @author Hajar
 */
public class Simulation extends javax.swing.JPanel {
    private SimulationFeuvrai s;
    private Graphics g;
    private int taille;
    /**
     * Creates new form Simulation
     */
    public Simulation(String sens, String vent, String humidite, double nbr, int ligne, int colonne, int taille) throws IOException {
        initComponents();
        this.taille = taille;
        s = new SimulationFeuvrai(sens, vent, humidite, nbr, ligne, colonne, taille);
        this.setSize(480,480);
    }
    
    public SimulationFeuvrai gets() {
        return s;
    }

    public void paint (Graphics g){      //méthode affichant notre terrain dans la partie graphique
        int t=0;
        int v=0;
        for (int x=0; x<sqrt(taille);x++){
            for (int y=0; y<sqrt(taille);y++){
                g.setColor(s.getForest()[x][y].getColorFromCase()); //appeler la méthode dans case
                t = 15+t;       //pour que les cases ne se superposent pas
                g.fillRect(t, v, 10, 11); 
                }
            v = 14+v;    //pour que les cases ne se superposent pas
            t = 0;
            }
        v = 0;
        }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(230, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
